query {
  gitea_repo(owner: "fixture", repo: "fixture-repo") {
    id
    owner {
      id
      login
      loginName
      sourceId
      fullName
      email
      avatarUrl
      htmlUrl
      language
      isAdmin
      lastLogin
      created
      restricted
      active
      prohibitLogin
      location
      website
      description
      visibility
      followersCount
      followingCount
      starredReposCount
    }
    name
    fullName
    description
    empty
    private
    fork
    template
    mirror
    size
    language
    languagesUrl
    htmlUrl
    url
    link
    sshUrl
    cloneUrl
    originalUrl
    website
    starsCount
    forksCount
    watchersCount
    openIssuesCount
    openPrCounter
    releaseCounter
    defaultBranch
    archived
    archivedAt
    createdAt
    updatedAt
    permissions {
      admin
      push
      pull
    }
    hasCode
    hasIssues
    hasWiki
    hasPullRequests
    hasProjects
    hasReleases
    hasPackages
    hasActions
    projectsMode
    topics
    licenses
    avatarUrl
    internal
    objectFormatName
  }
}
